#![no_std]
#![no_main]
#![feature(custom_test_frameworks)]
#![feature(abi_x86_interrupt)]
#![test_runner(crate::test_runner)]
#![reexport_test_harness_main = "test_main"]
extern crate alloc;

pub mod allocator;
pub mod io;
pub mod memory;
pub mod utils;

// pub use io::video::vga_buffer;
pub use io::serial;
pub use io::video::DISPLAY;
pub use io::console::CONSOLE;

use crate::io::{init_io, video};
use crate::memory::BootInfoFrameAllocator;
use bootloader_api::config::{BootloaderConfig, Mapping};
use bootloader_api::info::{MemoryRegionKind, MemoryRegions};
use bootloader_api::{entry_point, BootInfo};
use core::panic::PanicInfo;
use core::sync::atomic::{AtomicU8, Ordering};
use io::utils::qemu::{exit_qemu, QemuExitCode};
use x86_64::VirtAddr;

// Display mode requested from the firmware, generated by `build.rs` from
// `SIMPLOS_FB_WIDTH` / `SIMPLOS_FB_HEIGHT` (default 1920x1080). The UEFI path
// honours it through `BOOTLOADER_CONFIG` below; the BIOS path can't see the
// kernel config at all, so the vendored bootloader's stage-2 reads the same two
// variables at build time. Changing one no longer silently desyncs the other.
include!(concat!(env!("OUT_DIR"), "/framebuffer.rs"));

pub static BOOTLOADER_CONFIG: BootloaderConfig = {
    let mut config = BootloaderConfig::new_default();
    config.mappings.physical_memory = Some(Mapping::Dynamic);
    config.mappings.kernel_base = Mapping::FixedAddress(0x8000000000);
    config.frame_buffer.minimum_framebuffer_width = Some(FRAMEBUFFER_WIDTH);
    config.frame_buffer.minimum_framebuffer_height = Some(FRAMEBUFFER_HEIGHT);
    config
};

/// Firmware the bootloader handed us off from.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum BootMode {
    Uefi,
    Bios,
    Unknown,
}

impl BootMode {
    pub fn as_str(self) -> &'static str {
        match self {
            BootMode::Uefi => "UEFI",
            BootMode::Bios => "BIOS",
            BootMode::Unknown => "unknown",
        }
    }
}

static BOOT_MODE: AtomicU8 = AtomicU8::new(BootMode::Unknown as u8);

/// Boot mode detected during `pre_init`.
pub fn boot_mode() -> BootMode {
    match BOOT_MODE.load(Ordering::Relaxed) {
        x if x == BootMode::Uefi as u8 => BootMode::Uefi,
        x if x == BootMode::Bios as u8 => BootMode::Bios,
        _ => BootMode::Unknown,
    }
}

/// The boot info carries no firmware field, but the memory map does: regions the
/// bootloader could not classify keep their origin tag, which only one of the two
/// firmware paths ever produces.
fn detect_boot_mode(regions: &MemoryRegions) -> BootMode {
    for region in regions.iter() {
        match region.kind {
            MemoryRegionKind::UnknownUefi(_) => return BootMode::Uefi,
            MemoryRegionKind::UnknownBios(_) => return BootMode::Bios,
            _ => {}
        }
    }
    BootMode::Unknown
}

pub fn pre_init(boot_info: &'static mut BootInfo) {
    unsafe {
        init_io();
        BOOT_MODE.store(
            detect_boot_mode(&boot_info.memory_regions) as u8,
            Ordering::Relaxed,
        );
        let phys_mem_offset = VirtAddr::new(
            boot_info
                .physical_memory_offset
                .take()
                .expect("No physical memory offset found"),
        );
        let mut mapper = unsafe { memory::init(phys_mem_offset) };
        let mut frame_allocator =
            unsafe { BootInfoFrameAllocator::init(&boot_info.memory_regions) };
        allocator::init_heap(&mut mapper, &mut frame_allocator)
            .expect("heap initialization failed");
        
        // Initialize display with framebuffer
        let fb = boot_info.framebuffer.take().expect("No framebuffer found");
        let info = fb.info();
        video::init_display(fb);
        // Announce the mode we actually got. Under an emulator this is often the
        // only output that reaches the outside, and it is how you tell whether a
        // resolution change really took effect rather than silently falling back.
        serial_println!(
            "simplos: boot={} fb={}x{} stride={} bpp={} fmt={:?}",
            boot_mode().as_str(),
            info.width,
            info.height,
            info.stride,
            info.bytes_per_pixel,
            info.pixel_format
        );
        
        // Initialize HPET for high-precision timing
        if let Some(rsdp_addr) = boot_info.rsdp_addr.take() {
            if let Err(e) = io::hpet::init_hpet(rsdp_addr, phys_mem_offset) {
                // HPET init failed, continue without it
                serial_println!("HPET init failed: {}", e);
            }
        }
        
        x86_64::instructions::interrupts::enable();
    }
}

#[cfg(test)]
entry_point!(test_kernel_main, config = &BOOTLOADER_CONFIG);
#[cfg(test)]
fn test_kernel_main(boot_info: &'static mut BootInfo) -> ! {
    pre_init(boot_info);
    test_main();
    hlt_loop()
}

pub trait Testable {
    fn run(&self) -> ();
}
impl<T> Testable for T
where
    T: Fn(),
{
    fn run(&self) {
        serial_print!("{}...\t", core::any::type_name::<T>());
        self();
        serial_println!("[ok]");
    }
}

pub fn test_runner(tests: &[&dyn Testable]) {
    serial_println!("Running {} tests", tests.len());
    for test in tests {
        test.run();
    }
    exit_qemu(QemuExitCode::Success);
}

pub fn test_panic_handler(info: &PanicInfo) -> ! {
    serial_println!("[failed]\n");
    serial_println!("Error: {}\n", info);
    exit_qemu(QemuExitCode::Failed);
    loop {}
}
#[cfg(test)]
#[panic_handler]
fn panic(info: &PanicInfo) -> ! {
    test_panic_handler(info)
}

pub fn hlt_loop() -> ! {
    loop {
        x86_64::instructions::hlt();
    }
}


#[unsafe(no_mangle)]
pub fn badoo() {
    let a = 1;
    let b = 2;
    let c = a + b;
    core::hint::black_box(c);
}